#############################################################################
# Generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#  May 15, 2022 02:21:32 PM CST  platform: Darwin
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    button4_png "./button4.png" 
    button1_png "./button1.png" 
    button2_png "./button2.png" 
    button3_png "./button3.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #edf0f3
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m52" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x451+374+81
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1421
    wm minsize $top 120 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "BarcodeFinder"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "main" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 1 -command run_help \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image button4_png -pady 0 -text Button 
    vTcl:DefineAlias "$top.but46" "help_b" vTcl:WidgetProc "main" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 -command run_gb2fasta \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image button1_png -pady 0 -text Button 
    vTcl:DefineAlias "$top.but47" "gb2fasta_b" vTcl:WidgetProc "main" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 -command run_evaluate \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image button2_png -pady 0 -text Button 
    vTcl:DefineAlias "$top.but48" "evaluate_b" vTcl:WidgetProc "main" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 -command run_primer \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image button3_png -pady 0 -text Button 
    vTcl:DefineAlias "$top.but49" "primer_b" vTcl:WidgetProc "main" 1
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 1 -compound left \
        -font {-family {TkDefaultFont} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Install third-party software} 
    vTcl:DefineAlias "$top.but55" "Button2" vTcl:WidgetProc "main" 1
    label $top.lab52 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family Arial -size 20 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text GB2Fasta 
    vTcl:DefineAlias "$top.lab52" "Label1" vTcl:WidgetProc "main" 1
    label $top.lab53 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family Arial -size 20 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Evaluate 
    vTcl:DefineAlias "$top.lab53" "Label1_2" vTcl:WidgetProc "main" 1
    label $top.lab54 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family Arial -size 20 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Primer 
    vTcl:DefineAlias "$top.lab54" "Label1_2_1" vTcl:WidgetProc "main" 1
    label $top.lab55 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family Arial -size 20 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Click button to run modules} 
    vTcl:DefineAlias "$top.lab55" "Label2" vTcl:WidgetProc "main" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but46 \
        -in $top -x 0 -relx 0.913 -y 0 -rely 0.067 -width 40 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.188 -y 0 -rely 0.289 -width 100 -relwidth 0 \
        -height 100 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.438 -y 0 -rely 0.289 -width 100 -relwidth 0 \
        -height 100 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 550 -y 130 -width 100 -relwidth 0 -height 100 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.713 -y 0 -rely 0.865 -width 200 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.188 -y 0 -rely 0.532 -width 0 -relwidth 0.125 \
        -height 0 -relheight 0.067 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.45 -y 0 -rely 0.532 -width 0 -relwidth 0.125 \
        -height 0 -relheight 0.067 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.713 -y 0 -rely 0.532 -width 0 -relwidth 0.125 \
        -height 0 -relheight 0.067 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.621 -width 0 -relwidth 0.315 \
        -height 0 -relheight 0.078 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x800+414+142
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1421
    wm minsize $top 120 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "GB2Fasta"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "gb2fasta" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab58 \
        \
        -font {-family {TkDefaultFont} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text Input \
        -background $vTcl(actual_gui_bg) -height 367 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 573 
    vTcl:DefineAlias "$top.lab58" "Labelframe1" vTcl:WidgetProc "gb2fasta" 1
    set site_3_0 $top.lab58
    label $site_3_0.tLa61 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Genbank files} 
    vTcl:DefineAlias "$site_3_0.tLa61" "TLabel1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn62 \
        -font TkTextFont -textvariable gb -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn62" "gb_file" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn62 <<SetBalloon>> {
        set ::vTcl::balloon::%W {gb format files}
    }
    ttk::separator $site_3_0.tSe65
    vTcl:DefineAlias "$site_3_0.tSe65" "TSeparator1" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.tLa66 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Gene 
    vTcl:DefineAlias "$site_3_0.tLa66" "TLabel1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn67 \
        -font TkTextFont -textvariable gene -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn67" "gene" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn67 <<SetBalloon>> {
        set ::vTcl::balloon::%W {gene name}
    }
    ttk::separator $site_3_0.tSe69 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe69" "TSeparator1" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.tLa70 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Taxonomy 
    vTcl:DefineAlias "$site_3_0.tLa70" "TLabel1_1" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.tLa72 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Molecular 
    vTcl:DefineAlias "$site_3_0.tLa72" "TLabel1_2" vTcl:WidgetProc "gb2fasta" 1
    ttk::combobox $site_3_0.tCo75 \
        -values {all DNA RNA} -font TkTextFont -textvariable molecular \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo75" "TCombobox1" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.tLa76 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Group 
    vTcl:DefineAlias "$site_3_0.tLa76" "TLabel1_2_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::combobox $site_3_0.tCo77 \
        -values {all animals plants fungi protists bacteria archaea viruses} \
        -font TkTextFont -textvariable group -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo77" "TCombobox1_1" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.tLa78 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Organelle 
    vTcl:DefineAlias "$site_3_0.tLa78" "TLabel1_1_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::combobox $site_3_0.tCo79 \
        -values {ignore both no mitochondrion chloroplast} -font TkTextFont \
        -textvariable og -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo79" "og" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.tLa80 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text RefSeq 
    vTcl:DefineAlias "$site_3_0.tLa80" "TLabel1_1_1_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::combobox $site_3_0.tCo81 \
        -values {both yes no} -font TkTextFont -textvariable refseq \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo81" "refseq" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tCo81 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Use RefSeq or not}
    }
    label $site_3_0.tLa82 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Count 
    vTcl:DefineAlias "$site_3_0.tLa82" "TLabel1_1_1_1_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn83 \
        -font TkTextFont -textvariable count -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn83" "TEntry1" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn83 <<SetBalloon>> {
        set ::vTcl::balloon::%W {numbers of sequences to download}
    }
    label $site_3_0.tLa84 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Length 
    vTcl:DefineAlias "$site_3_0.tLa84" "TLabel1_2_1_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn87 \
        -font TkTextFont -textvariable min_len -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn87" "gb_file_1_2" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.lab88 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text to 
    vTcl:DefineAlias "$site_3_0.lab88" "Label1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn89 \
        -font TkTextFont -textvariable max_len -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn89" "gb_file_1_2_1" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.tLa90 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Date 
    vTcl:DefineAlias "$site_3_0.tLa90" "TLabel1_2_1_1_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn91 \
        -font TkTextFont -textvariable date_start -foreground {} \
        -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn91" "gb_file_1_2_2" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn91 <<SetBalloon>> {
        set ::vTcl::balloon::%W {1970/1/1}
    }
    label $site_3_0.lab92 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text to 
    vTcl:DefineAlias "$site_3_0.lab92" "Label1_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn93 \
        -font TkTextFont -textvariable date_end -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn93" "gb_file_1_2_1_1" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn93 <<SetBalloon>> {
        set ::vTcl::balloon::%W {2022/12/31}
    }
    label $site_3_0.tLa99 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Exclude 
    vTcl:DefineAlias "$site_3_0.tLa99" "TLabel1_1_1_1_1_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn100 \
        -font TkTextFont -textvariable exclude -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn100" "gb_file_1_2_2_1" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn100 <<SetBalloon>> {
        set ::vTcl::balloon::%W {1970/1/1}
    }
    label $site_3_0.tLa101 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Query 
    vTcl:DefineAlias "$site_3_0.tLa101" "TLabel1_1_1_1_1_2" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn102 \
        -font TkTextFont -textvariable query -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn102" "TEntry1" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn102 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Entrez query string}
    }
    button $site_3_0.but131 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Open 
    vTcl:DefineAlias "$site_3_0.but131" "Button1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn135 \
        -font TkTextFont -textvariable taxon -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn135" "taxon" vTcl:WidgetProc "gb2fasta" 1
    place $site_3_0.tLa61 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.057 -width 0 \
        -relwidth 0.157 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn62 \
        -in $site_3_0 -x 0 -relx 0.241 -y 0 -rely 0.057 -width 0 \
        -relwidth 0.562 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe65 \
        -in $site_3_0 -x 0 -relx 0.002 -y 0 -rely 0.171 -width 0 \
        -relwidth 0.995 -height 0 -relheight 0.011 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa66 \
        -in $site_3_0 -x 0 -relx 0.035 -y 0 -rely 0.217 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn67 \
        -in $site_3_0 -x 0 -relx 0.201 -y 0 -rely 0.217 -width 0 \
        -relwidth 0.314 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe69 \
        -in $site_3_0 -x 0 -relx 0.524 -y 0 -rely 0.19 -width 0 \
        -relwidth 0.005 -height 0 -relheight 0.542 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa70 \
        -in $site_3_0 -x 0 -relx 0.035 -y 0 -rely 0.325 -width 0 \
        -relwidth 0.122 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa72 \
        -in $site_3_0 -x 0 -relx 0.558 -y 0 -rely 0.217 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo75 \
        -in $site_3_0 -x 0 -relx 0.719 -y 0 -rely 0.217 -width 0 \
        -relwidth 0.257 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa76 \
        -in $site_3_0 -x 0 -relx 0.558 -y 0 -rely 0.325 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo77 \
        -in $site_3_0 -x 0 -relx 0.719 -y 0 -rely 0.325 -width 0 \
        -relwidth 0.257 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa78 \
        -in $site_3_0 -x 0 -relx 0.035 -y 0 -rely 0.434 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo79 \
        -in $site_3_0 -x 0 -relx 0.201 -y 0 -rely 0.434 -width 0 \
        -relwidth 0.314 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa80 \
        -in $site_3_0 -x 0 -relx 0.035 -y 0 -rely 0.542 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo81 \
        -in $site_3_0 -x 0 -relx 0.201 -y 0 -rely 0.542 -width 0 \
        -relwidth 0.314 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa82 \
        -in $site_3_0 -x 0 -relx 0.035 -y 0 -rely 0.65 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn83 \
        -in $site_3_0 -x 0 -relx 0.201 -y 0 -rely 0.65 -width 0 \
        -relwidth 0.314 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa84 \
        -in $site_3_0 -x 0 -relx 0.558 -y 0 -rely 0.434 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn87 \
        -in $site_3_0 -x 0 -relx 0.686 -y 0 -rely 0.434 -width 0 \
        -relwidth 0.086 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 0 -relx 0.789 -y 0 -rely 0.434 -width 0 \
        -relwidth 0.063 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn89 \
        -in $site_3_0 -x 0 -relx 0.839 -y 0 -rely 0.434 -width 0 \
        -relwidth 0.14 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa90 \
        -in $site_3_0 -x 0 -relx 0.558 -y 0 -rely 0.542 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn91 \
        -in $site_3_0 -x 0 -relx 0.686 -y 0 -rely 0.542 -width 0 \
        -relwidth 0.086 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab92 \
        -in $site_3_0 -x 0 -relx 0.789 -y 0 -rely 0.542 -width 0 \
        -relwidth 0.063 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn93 \
        -in $site_3_0 -x 0 -relx 0.839 -y 0 -rely 0.542 -width 0 \
        -relwidth 0.136 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa99 \
        -in $site_3_0 -x 0 -relx 0.558 -y 0 -rely 0.65 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn100 \
        -in $site_3_0 -x 0 -relx 0.686 -y 0 -rely 0.65 -width 0 \
        -relwidth 0.279 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa101 \
        -in $site_3_0 -x 0 -relx 0.035 -y 0 -rely 0.813 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn102 \
        -in $site_3_0 -x 0 -relx 0.201 -y 0 -rely 0.813 -width 0 \
        -relwidth 0.785 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but131 \
        -in $site_3_0 -x 0 -relx 0.82 -y 0 -rely 0.054 -width 90 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn135 \
        -in $site_3_0 -x 0 -relx 0.201 -y 0 -rely 0.325 -width 0 \
        -relwidth 0.314 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    label $top.tLa103 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Output 
    vTcl:DefineAlias "$top.tLa103" "TLabel1_1_1_1_1_2_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $top.tEn104 \
        -font TkTextFont -textvariable out -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$top.tEn104" "gb_file_2" vTcl:WidgetProc "gb2fasta" 1
    bind $top.tEn104 <<SetBalloon>> {
        set ::vTcl::balloon::%W {output folder}
    }
    labelframe $top.lab106 \
        \
        -font {-family {TkDefaultFont} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text Advance \
        -background $vTcl(actual_gui_bg) -height 151 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 590 
    vTcl:DefineAlias "$top.lab106" "Labelframe1" vTcl:WidgetProc "gb2fasta" 1
    set site_3_0 $top.lab106
    checkbutton $site_3_0.che110 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text {Allow repeat} \
        -variable allow_repeat 
    vTcl:DefineAlias "$site_3_0.che110" "Checkbutton1_1_1" vTcl:WidgetProc "gb2fasta" 1
    checkbutton $site_3_0.che111 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text {Allow invert repeat} \
        -variable allow_invert_repeat 
    vTcl:DefineAlias "$site_3_0.che111" "Checkbutton1_1_1_1" vTcl:WidgetProc "gb2fasta" 1
    checkbutton $site_3_0.che112 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text {Allow mosaic repeat} \
        -variable allow_mosaic_repeat 
    vTcl:DefineAlias "$site_3_0.che112" "Checkbutton1_1_1_1_1" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.tLa115 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Expand 
    vTcl:DefineAlias "$site_3_0.tLa115" "TLabel1_1_1_1_1_2_2_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn116 \
        -font TkTextFont -textvariable expand -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn116" "gb_file_1_2_1_1_1" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn116 <<SetBalloon>> {
        set ::vTcl::balloon::%W {expand for primer design}
    }
    label $site_3_0.tLa117 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Max name length} 
    vTcl:DefineAlias "$site_3_0.tLa117" "TLabel1_1_1_1_1_2_2_1_1" vTcl:WidgetProc "gb2fasta" 1
    label $site_3_0.tLa118 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Max fragment length} 
    vTcl:DefineAlias "$site_3_0.tLa118" "TLabel1_1_1_1_1_2_2_1_1_1" vTcl:WidgetProc "gb2fasta" 1
    ttk::entry $site_3_0.tEn119 \
        -font TkTextFont -textvariable max_name_len -foreground {} \
        -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn119" "gb_file_1_2_1_1_1_1" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn119 <<SetBalloon>> {
        set ::vTcl::balloon::%W {max feature name length}
    }
    ttk::entry $site_3_0.tEn120 \
        -font TkTextFont -textvariable max_gene_len -foreground {} \
        -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn120" "gb_file_1_2_1_1_1_2" vTcl:WidgetProc "gb2fasta" 1
    bind $site_3_0.tEn120 <<SetBalloon>> {
        set ::vTcl::balloon::%W {max fragment sequence length}
    }
    ttk::separator $site_3_0.tSe46 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe46" "TSeparator2" vTcl:WidgetProc "gb2fasta" 1
    place $site_3_0.che110 \
        -in $site_3_0 -x 0 -relx 0.576 -y 0 -rely 0.142 -width 0 \
        -relwidth 0.276 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che111 \
        -in $site_3_0 -x 0 -relx 0.576 -y 0 -rely 0.709 -width 0 \
        -relwidth 0.361 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che112 \
        -in $site_3_0 -x 0 -relx 0.576 -y 0 -rely 0.426 -width 0 \
        -relwidth 0.361 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa115 \
        -in $site_3_0 -x 0 -relx 0.175 -y 0 -rely 0.142 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn116 \
        -in $site_3_0 -x 0 -relx 0.297 -y 0 -rely 0.142 -width 0 \
        -relwidth 0.187 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa117 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.426 -width 0 \
        -relwidth 0.209 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa118 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.709 -width 0 \
        -relwidth 0.227 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn119 \
        -in $site_3_0 -x 0 -relx 0.297 -y 0 -rely 0.426 -width 0 \
        -relwidth 0.187 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn120 \
        -in $site_3_0 -x 0 -relx 0.297 -y 0 -rely 0.709 -width 0 \
        -relwidth 0.187 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe46 \
        -in $site_3_0 -x 0 -relx 0.524 -y 0 -rely 0.135 -width 0 \
        -relwidth 0.002 -height 0 -relheight 0.78 -anchor nw \
        -bordermode ignore 
    checkbutton $top.che126 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text {No divide} \
        -variable no_divide 
    vTcl:DefineAlias "$top.che126" "Checkbutton1" vTcl:WidgetProc "gb2fasta" 1
    checkbutton $top.che127 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text {Rename gene} \
        -variable rename 
    vTcl:DefineAlias "$top.che127" "Checkbutton1_1" vTcl:WidgetProc "gb2fasta" 1
    label $top.tLa128 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Unique 
    vTcl:DefineAlias "$top.tLa128" "TLabel1_1_1_1_1_2_2" vTcl:WidgetProc "gb2fasta" 1
    ttk::combobox $top.tCo129 \
        -values {longest first no} -font TkTextFont -textvariable unique \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo129" "TCombobox1_2" vTcl:WidgetProc "gb2fasta" 1
    bind $top.tCo129 <<SetBalloon>> {
        set ::vTcl::balloon::%W {methods to remove redundant records}
    }
    button $top.but132 \
        -activebackground #edf0f3 -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Open 
    vTcl:DefineAlias "$top.but132" "Button1_1" vTcl:WidgetProc "gb2fasta" 1
    button $top.but133 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command run_gb2fasta -compound left \
        -font {-family {TkDefaultFont} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Run 
    vTcl:DefineAlias "$top.but133" "Button1" vTcl:WidgetProc "gb2fasta" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab58 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.013 -width 0 -relwidth 0.955 \
        -height 0 -relheight 0.46 -anchor nw -bordermode ignore 
    place $top.tLa103 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.563 -width 0 -relwidth 0.1 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.tEn104 \
        -in $top -x 0 -relx 0.167 -y 0 -rely 0.563 -width 0 -relwidth 0.633 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.lab106 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.65 -width 0 -relwidth 0.955 \
        -height 0 -relheight 0.176 -anchor nw -bordermode ignore 
    place $top.che126 \
        -in $top -x 0 -relx 0.733 -y 0 -rely 0.487 -width 0 -relwidth 0.215 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.che127 \
        -in $top -x 0 -relx 0.467 -y 0 -rely 0.487 -width 0 -relwidth 0.243 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.tLa128 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.487 -width 0 -relwidth 0.115 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.tCo129 \
        -in $top -x 0 -relx 0.167 -y 0 -rely 0.487 -width 0 -relwidth 0.245 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.but132 \
        -in $top -x 0 -relx 0.833 -y 0 -rely 0.563 -width 80 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but133 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.863 -width 189 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top46 {base} {
    global vTcl
    if {$base == ""} {
        set base .top46
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+641+332
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1728 997
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Evaluate"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "evaluate" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Input \
        -background $vTcl(actual_gui_bg) -height 75 -width 150 
    vTcl:DefineAlias "$top.lab46" "Labelframe1" vTcl:WidgetProc "evaluate" 1
    set site_3_0 $top.lab46
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Unaligned FASTA files} 
    vTcl:DefineAlias "$site_3_0.lab47" "TLabel1" vTcl:WidgetProc "evaluate" 1
    bind $site_3_0.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {unaligned}
    }
    ttk::entry $site_3_0.tEn48 \
        -font TkTextFont -textvariable fasta -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn48" "gb_file" vTcl:WidgetProc "evaluate" 1
    bind $site_3_0.tEn48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {unaligned fasta files}
    }
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1" vTcl:WidgetProc "evaluate" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Unaligned FASTA folder} 
    vTcl:DefineAlias "$site_3_0.lab50" "TLabel1" vTcl:WidgetProc "evaluate" 1
    bind $site_3_0.lab50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {unaligned}
    }
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Aligned FASTA files} 
    vTcl:DefineAlias "$site_3_0.lab51" "TLabel1_3" vTcl:WidgetProc "evaluate" 1
    bind $site_3_0.lab51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {unaligned}
    }
    ttk::entry $site_3_0.tEn52 \
        -font TkTextFont -textvariable fasta_folder -foreground {} \
        -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn52" "gb_file" vTcl:WidgetProc "evaluate" 1
    bind $site_3_0.tEn52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {unaligned fasta files}
    }
    ttk::entry $site_3_0.tEn53 \
        -font TkTextFont -textvariable aln -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn53" "gb_file_1" vTcl:WidgetProc "evaluate" 1
    bind $site_3_0.tEn53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {unaligned fasta files}
    }
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Open 
    vTcl:DefineAlias "$site_3_0.but54" "Button1" vTcl:WidgetProc "evaluate" 1
    button $site_3_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Open 
    vTcl:DefineAlias "$site_3_0.but55" "Button1_2" vTcl:WidgetProc "evaluate" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.227 -height 0 -relheight 0.233 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn48 \
        -in $site_3_0 -x 0 -relx 0.314 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.489 -height 0 -relheight 0.233 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.82 -y 0 -rely 0.133 -width 90 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.4 -width 0 \
        -relwidth 0.244 -height 0 -relheight 0.233 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.157 -height 0 -relheight 0.233 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn52 \
        -in $site_3_0 -x 0 -relx 0.314 -y 0 -rely 0.4 -width 0 \
        -relwidth 0.489 -height 0 -relheight 0.233 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn53 \
        -in $site_3_0 -x 0 -relx 0.314 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.489 -height 0 -relheight 0.233 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.82 -y 0 -rely 0.4 -width 90 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 0 -relx 0.82 -y 0 -rely 0.667 -width 90 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Output folder} 
    vTcl:DefineAlias "$top.lab56" "TLabel1_3_1" vTcl:WidgetProc "evaluate" 1
    bind $top.lab56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {unaligned}
    }
    ttk::entry $top.tEn57 \
        -font TkTextFont -textvariable out -foreground {} -background {} \
        -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$top.tEn57" "gb_file_1_1" vTcl:WidgetProc "evaluate" 1
    bind $top.tEn57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {unaligned fasta files}
    }
    button $top.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font {-family {TkDefaultFont} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Open 
    vTcl:DefineAlias "$top.but58" "Button1_2_1" vTcl:WidgetProc "evaluate" 1
    labelframe $top.lab59 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Sliding window} -background $vTcl(actual_gui_bg) -height 75 \
        -width 150 
    vTcl:DefineAlias "$top.lab59" "Labelframe1" vTcl:WidgetProc "evaluate" 1
    set site_3_0 $top.lab59
    checkbutton $site_3_0.che61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #edf0f3 -text {Skip sliding window} \
        -variable quick 
    vTcl:DefineAlias "$site_3_0.che61" "Checkbutton1" vTcl:WidgetProc "evaluate" 1
    label $site_3_0.lab63 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Window size} 
    vTcl:DefineAlias "$site_3_0.lab63" "Label1" vTcl:WidgetProc "evaluate" 1
    entry $site_3_0.ent64 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -textvariable size -width 10 
    vTcl:DefineAlias "$site_3_0.ent64" "Entry1" vTcl:WidgetProc "evaluate" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Step length} 
    vTcl:DefineAlias "$site_3_0.lab65" "Label1_3" vTcl:WidgetProc "evaluate" 1
    entry $site_3_0.ent66 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable step -width 10 
    vTcl:DefineAlias "$site_3_0.ent66" "Entry1_1" vTcl:WidgetProc "evaluate" 1
    place $site_3_0.che61 \
        -in $site_3_0 -x 0 -relx 0.035 -y 0 -rely 0.429 -width 0 \
        -relwidth 0.262 -height 0 -relheight 0.3 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.314 -y 0 -rely 0.429 -width 0 \
        -relwidth 0.14 -height 0 -relheight 0.314 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent64 \
        -in $site_3_0 -x 0 -relx 0.471 -y 0 -rely 0.429 -width 100 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.681 -y 0 -rely 0.429 -width 0 \
        -relwidth 0.14 -height 0 -relheight 0.314 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 0 -relx 0.82 -y 0 -rely 0.429 -width 80 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab60 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Advance \
        -background $vTcl(actual_gui_bg) -height 75 -width 150 
    vTcl:DefineAlias "$top.lab60" "Labelframe1" vTcl:WidgetProc "evaluate" 1
    set site_3_0 $top.lab60
    checkbutton $site_3_0.che67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #edf0f3 -text {Ignore gaps in alignment} \
        -variable ig 
    vTcl:DefineAlias "$site_3_0.che67" "Checkbutton1" vTcl:WidgetProc "evaluate" 1
    checkbutton $site_3_0.che68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #edf0f3 -text {Ignore ambiguous bases} \
        -variable iab 
    vTcl:DefineAlias "$site_3_0.che68" "Checkbutton1_2" vTcl:WidgetProc "evaluate" 1
    place $site_3_0.che67 \
        -in $site_3_0 -x 0 -relx 0.087 -y 0 -rely 0.429 -width 0 \
        -relwidth 0.314 -height 0 -relheight 0.3 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che68 \
        -in $site_3_0 -x 0 -relx 0.593 -y 0 -rely 0.429 -width 0 \
        -relwidth 0.314 -height 0 -relheight 0.3 -anchor nw \
        -bordermode ignore 
    button $top.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command run_evaluate -compound left \
        -font {-family {TkDefaultFont} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief raised -text Run 
    vTcl:DefineAlias "$top.but69" "Button1_3" vTcl:WidgetProc "evaluate" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.017 -y 0 -width 0 -relwidth 0.955 -height 0 \
        -relheight 0.333 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.356 -width 0 -relwidth 0.15 \
        -height 0 -relheight 0.078 -anchor nw -bordermode ignore 
    place $top.tEn57 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.356 -width 0 -relwidth 0.467 \
        -height 0 -relheight 0.078 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.8 -y 0 -rely 0.356 -width 90 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.467 -width 0 -relwidth 0.955 \
        -height 0 -relheight 0.156 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.644 -width 0 -relwidth 0.955 \
        -height 0 -relheight 0.156 -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.867 -width 189 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top47 {base} {
    global vTcl
    if {$base == ""} {
        set base .top47
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x500+414+372
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1728 997
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Primer"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "primer" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ###################
    # SETTING GEOMETRY
    ###################
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top44 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top45 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top46 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}
set btop4 ""
if {$vTcl(borrow)} {
    set btop4 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop4 $vTcl(tops)] != -1} {
        set btop4 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop4
Window show .top47 $btop4
if {$vTcl(borrow)} {
    $btop4 configure -background plum
}

